kind: Namespace
apiVersion: v1
metadata:
  name: istio-system
  labels:
    name: istio-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: argo-app-of-apps
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      ref: argo-repo
    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      chart: istio-base
      targetRevision: 1.17.0 # Update this to a valid version
      helm:
        valueFiles:
          - $argo-repo/apps/cilium/values/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  hooks:
    - type: PreSync
      resource:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: kube-system