kind: Namespace
apiVersion: v1
metadata:
  name: cilium
  labels:
    name: cilium
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      ref: argo-repo
    - repoURL: 'https://helm.cilium.io/'
      chart: cilium
      targetRevision: 1.15.1 # Update this to a valid version
      helm:
        valueFiles:
          - $argo-repo/apps/cilium/values/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  hooks:
    - type: PreSync
      resource:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: kube-system