apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: argo-app-of-apps
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      ref: prometheus-repo
    - chart: istiod
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.24.0  # Update this to a valid version
      helm:
        valueFiles:
          - $prometheus-repo/apps/istio/values/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # syncOptions:
  #   - CreateNamespace=true
  # hooks:
  #   - type: PreSync
  #     resource:
  #       apiVersion: v1
  #       kind: Namespace
  #       metadata:
  #         name: istio-system
---
# apps/istio/gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
# apps/istio/virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /prometheus
    route:
    - destination:
        host: prometheus-server.prometheus.svc.cluster.local
        port:
          number: 9090
  - match:
    - uri:
        prefix: /grafana
    route:
    - destination:
        host: grafana.grafana.svc.cluster.local
        port:
          number: 3000
  - match:
    - uri:
        prefix: /loki
    route:
    - destination:
        host: loki.loki.svc.cluster.local
        port:
          number: 3100