apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: argo-app-of-apps
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      ref: prometheus-repo
    - chart: istiod
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.24.0  # Update this to a valid version
      helm:
        valueFiles:
          - $prometheus-repo/apps/istio/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  hooks:
    - type: PreSync
      resource:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: istio-system