apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: argo-app-of-apps
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      ref: prometheus-repo
    - chart: cert-manager    
      repoURL: 'https://github.com/cert-manager/cert-manager'
      targetRevision: v1.16.2  # Update this to a valid version
      helm:
        valueFiles:
          - $prometheus-repo/apps/cert-manager/values/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

