apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milenkom-k8s-com
  namespace: cert-manager
spec:
  secretName: milenkom-k8s-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: milenkom-k8s.com
  dnsNames:
  - milenkom-k8s.com
  - www.milenkom-k8s.com