apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: milenkom-k8s.com
  dnsNames:
  - milenkom-k8s.com
  - www.milenkom-k8s.com