# apps/istio/values.yaml
global:
  proxy:
    autoInject: enabled
    logLevel: info
pilot:
  traceSampling: 100

# Enable CRDs installation
istio_cni:
  enabled: true

# Enable Kiali
kiali:
  enabled: true
  dashboard:
    auth:
      strategy: anonymous

# Enable Jaeger
tracing:
  enabled: true
  provider: jaeger