# apps/grafana-loki/values.yaml
loki:
  config: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    memberlist:
      join_members:
        - loki-memberlist
    schema_config:
      configs:
        - from: 2022-01-11
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

# Ensure the storage paths are writable
persistence:
  enabled: true
  storageClassName: "standard"  # Update this to your storage class
  accessModes:
    - ReadWriteOnce
  size: 10Gi