loki:
  servicemonitor:
  enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    # Remove invalid fields
    # allow_structured_metadata: true
    # volume_enabled: true

deploymentMode: Distributed

ingester:
  replicas: 3 # To ensure data durability with replication
querier:
  replicas: 3 # Improve query performance via parallelism
  maxUnavailable: 2
queryFrontend:
  replicas: 2
  maxUnavailable: 1
queryScheduler:
  replicas: 2

# Storage configuration for local filesystem
storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks

persistence:
  enabled: true
  storageClassName: "standard"  # Update this to your storage class
  accessModes:
    - ReadWriteOnce
  size: 10Gi