apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-namespace-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-namespace-manager
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd