apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
    targetRevision: main
    path: apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Define the child applications
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/prometheus.yaml
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/grafana
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/grafana-loki