apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  project: argo-app-of-apps
  source:
    repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
    targetRevision: main
    path: apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  # Define the child applications
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/prometheus
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/grafana
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/grafana-loki
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/istio
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/cert-manager
