apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  project: argo-app-of-apps
  source:
    repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
    targetRevision: main
    path: apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Define the child applications
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/prometheus
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/grafana
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/grafana-loki
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      path: apps/cilium
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: my-oci-charts
stringData:
  enableOCI: "true"
  type: helm 
  url: oci://registry-1.docker.io/bitnamicharts/cilium
