apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: argo-app-of-apps
  sources:
    - repoURL: 'git@github.com:subzone/argocd-app-of-apps.git'
      targetRevision: main
      ref: prometheus-repo
    - chart: grafana    
      repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 8.6.4  # Update this to a valid version
      helm:
        valueFiles:
          - $prometheus-repo/apps/grafana/values/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

