apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argoappofapps
spec:
  project: prometheus
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 3.0.0
    helm:
      valueFiles:
        - apps/prometheus/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    hooks:
    - type: PreSync
      resource:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: prometheus
---
