apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: argo-app-of-apps
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus-community/prometheus
    targetRevision: 26.0.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    hooks:
    - type: PreSync
      resource:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: prometheus
